[package]
name = "toolbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.5.1"
rfd = "0.14.1"
walkdir = "2"

[build-dependencies]
slint-build = "1.5.1"
