import { HorizontalBox, ComboBox, TextEdit, Button, ScrollView, CheckBox } from "std-widgets.slint";
import { CheckedItem } from "models.slint";
export component SelectWithTip inherits HorizontalBox {
    in property <string> tip;
    in property <[string]> selections;
    in-out property <string> selection <=> selection.current-value;
    in-out property <int> index <=> selection.current-index;
    Text {
        vertical-alignment: center;
        width: parent.width / 3;
        text: tip;
    }
    selection := ComboBox {
        width: parent.width / 2;
        current-index: 0;
        model: selections;
    }
}

export component DirPickerWithTip inherits HorizontalBox {
    in property <string> tip;
    in-out property <string> path <=> path.text;
    in-out property <bool> can_edit <=> path.enabled;
    callback select_dir() -> string;
    Text {
        vertical-alignment: center;
        width: parent.width / 3;
        text: tip;
    }
    path := TextEdit {
        width: parent.width / 2;
        wrap: TextWrap.no-wrap;
        text: "";
    }
    Button {
        text: "选择";
        colorize-icon: true;
        clicked => {
            path.text = root.select_dir()
        }
    }
}

export component InputWithTip inherits HorizontalBox {
    in property <string> tip;
    in-out property <string> input <=> input.text;
    Text {
        width: parent.width / 3;
        vertical-alignment: center;
        text: tip;
    }
    input := TextEdit {
        width: parent.width / 2;
        text: "";
    }
}

export component MultiLinesTip inherits HorizontalBox {
    in property <string> tip;
    TextEdit {
        read-only: true;
        wrap: TextWrap.word-wrap;
        text: tip;
    }
}


export component ButtonGroup inherits HorizontalBox {
    callback clear();
    callback run();
    spacing: 500px;
    alignment: center;
    Button {
        width: 60px;
        height: 40px;
        text: "清除";
        colorize-icon: true;
        clicked => {
            root.clear()
        }
    }
    Button {
        width: 60px;
        height: 40px;
        text: "运行";
        colorize-icon: true;
        clicked => {
            root.run()
        }
    }
    
}

export component ScollCheckBox inherits HorizontalBox {
    in property <string> tip;
    in-out property <[CheckedItem]> items;
    Text {
        vertical-alignment: center;
        width: parent.width / 3;
        text: tip;
    }
    ScrollView {
        width: parent.width / 2;
        viewport-width: self.width;
        viewport-height: max(self.height, (items.length + 1) * 20px);
        
        for item[i] in items: CheckBox {
            x: parent.x;
            y: parent.y + i * self.height;
            height: 20px;
            text: item.item;
            checked: item.checked;
            toggled => {
                if self.checked {
                    items[i].checked = true
                } else {
                    items[i].checked = false
                }
            }
        }

    }
}

export component CheckBoxWithTip inherits HorizontalBox {
    in property <string> tip;
    in-out property <bool> checked <=> box.checked;
    Text {
        vertical-alignment: center;
        width: parent.width / 3;
        text: tip;
    }
    box := CheckBox {
        height: parent.height / 2;
        width: parent.width / 2;
        text: "删除源文件";
    }
}

export component Space inherits HorizontalLayout{
    
}