import { VerticalBox, HorizontalBox, ComboBox, Button, TextEdit } from "std-widgets.slint";
import { FuncName } from "models.slint";

export component RenameFilesPanel inherits VerticalBox {
    in-out property <FuncName> name;
    callback select_path() -> string;
    HorizontalBox {
        height: parent.height * (1/6);
        // width: parent.width;
        Text {
            vertical-alignment: center;
            // height: parent.height;
            width: parent.width / 3;
            text: "请选择批量修改方法：";
        }
        ComboBox {
            height: parent.height / 2;
            // y: parent.y;
            width: parent.width / 2;
            current-index: 0;
            model: [
                "批量移除指定字符",
                "批量移除指定前缀",
                "批量移除指定后缀",
                "批量新增指定前缀",
                "批量新增指定后缀",
                "批量替换指定前缀",
                "批量替换指定后缀",
            ];
        }
    }
    HorizontalBox {
        height: parent.height * (1/6);
        // width: parent.width;
        Text {
            // height: parent.height;
            vertical-alignment: center;
            width: parent.width / 3;
            text: "请选择批量路径：";
        }
        path:= TextEdit {
            height: parent.height / 2;
            // y: parent.y;
            width: parent.width / 3;
            text: "/";
        }
        Button {
            height: parent.height / 2;
            // y: parent.y;
            text: "选择";
            colorize-icon: true;
            width: 60px;
            clicked => {
                path.text = root.select_path()
            }
        }
    }
    HorizontalBox {
        height: parent.height * (1/6);
        // width: parent.width;
        Text {
            // height: parent.height;
            width: parent.width / 3;
            vertical-alignment: center;
            text: "请指定字符：";
        }
        specify_characters := TextEdit {
            height: parent.height / 2;
            // y: parent.y;
            width: parent.width / 2;
            text: "旧字符串批量替换至新字符串";
        }
        
    }
    HorizontalBox {
        height: parent.height * (1/8);
        TextEdit {
            read-only: true;
            wrap: TextWrap.word-wrap;
            height: parent.height;
            text: "注意：替换字符类方法须同时提供旧字符和新字符，并使用'批量替换至'连接。例如：旧字符串批量替换至新字符串";
        }
        
    }
    HorizontalBox {
        height: parent.height * (1/6);
        width: parent.width;
        Button {
            // height: 20px;
            width: 60px;
            text: "清除";
            colorize-icon: true;
        }
        HorizontalBox {
            height: parent.height;
            width: 260px;
        }
        Button {
            // height: 20px;
            width: 60px;
            text: "运行";
            colorize-icon: true;
        }
        
    }
}