import { VerticalBox, HorizontalBox, ComboBox, Button, TextEdit } from "std-widgets.slint";
import { RenameFilesRun } from "models.slint";
import { SelectWithTip, DirPickerWithTip, InputWithTip, MultiLinesTip, ButtonGroup, Space } from "common.slint";

export component RenameFilesPanel inherits VerticalBox {
    out property <[string]> methods: [
        "批量移除指定字符",
        "批量移除指定前缀",
        "批量移除指定后缀",
        "批量新增指定前缀",
        "批量新增指定后缀",
        "批量替换指定前缀",
        "批量替换指定后缀",
    ];
    in-out property <RenameFilesRun> run_info: {
        method: method.selection,
        path: path.path,
        specify_characters: specify_characters.input,
    };
    callback select_dir() -> string;
    callback run(RenameFilesRun);
    spacing: 40px;
    alignment: center;


    method := SelectWithTip {
        height: 60px;
        tip: "请选择批量修改方法：";
        selections: root.methods;
    }


    path := DirPickerWithTip {
        height: 60px;
        tip: "请选择操作路径：";
        can_edit: true;
        select_dir => {
            return root.select_dir();
        }
    }


    specify_characters := InputWithTip {
        height: 60px;
        tip: "请指定字符：";
    }


    MultiLinesTip {
        height: 80px;
        tip: "注意：替换字符类方法须同时提供旧字符和新字符，并使用'-批量替换至-'连接。例如：旧字符串批量替换至新字符串";
    }

    

    ButtonGroup {
        height: 80px;
        clear => {
            method.index = 0;
            method.selection = method.selections[method.index];
            path.path = "";
            specify-characters.input = "";
        }
        run => {
            root.run(run_info)
        }
    }
}