import { Button, ComboBox, CheckBox, HorizontalBox, VerticalBox, ScrollView} from "std-widgets.slint";
import { RenameFilesPanel } from "rename_files_panel.slint";
import { RenameFilesRun, ExtractFilesRun, CheckedItem } from "models.slint";
import { ExtractFilesPanel } from "extract_files_panel.slint";
import { FuncListPanel } from "func_list_panel.slint";










export component MainWindow inherits Window {
    height: 400px;
    width: 600px;
    title: "工具箱";
    background: black;
    icon: @image-url("../images/tools.png");


    in-out property <string> cur_func_name <=> func-list.cur_func_name;

    callback select_dir() -> string;
    callback run_rename_files(RenameFilesRun);
    callback run_extract_files(ExtractFilesRun);
    callback get_extensions(string) -> [CheckedItem];
    glb := HorizontalBox {
        height: parent.height;
        width: parent.width;
        // func_icons := VerticalLayout {
        //     height: parent.height - (self.y * 2);
        //     width: parent.width * (1 / 6);
        //     ScrollView {
        //         height: parent.height;
        //         width: parent.width;
        //         viewport-height: max(parent.height, 4 * 100px);
        //         for func[i] in func_infos: Func {
        //             x: parent.x;
        //             y: i * (parent.height / 4);
        //             height: 82px;
        //             width: 82px;
        //             name: func.name;
        //             is_cur: func.is_cur;
        //             clicked => {
        //                 click_func(self.name);
        //             }
        //         }
        //     }
        // }
        func_list := FuncListPanel{
            height: parent.height - (self.y * 2);
            width: parent.width * (1 / 6);
        }

        detail := HorizontalLayout {
            height: parent.height;
            width: parent.width * (5 / 6);

            if cur_func_name == "修改文件路径": RenameFilesPanel {
                height: parent.height;
                width: parent.width;
                select_dir => {
                    return root.select_dir();
                }
                run(run_info) => {
                    root.run_rename_files(run_info)
                }
            } 
            if cur_func_name == "提取文件": ExtractFilesPanel {
                height: parent.height;
                width: parent.width;
                select_dir => {
                    root.select_dir()
                }
                run(run_info) => {
                    root.run_extract_files(run_info)
                }
                origin_selected(s) => {
                    root.get_extensions(s)
                }
            }
            if cur_func_name == "对比剪贴板": VerticalBox {
                height: parent.height;
                width: parent.width;
                Text {
                    text: "对比剪贴板";
                }
            }
            if cur_func_name == "推送安卓文件": VerticalBox {
                height: parent.height;
                width: parent.width;
                Text {
                    text: "推送安卓文件";
                }
            }

    }
}

}
